## 1. Importing Library

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

## 2. Importing Dataset

In [145]:
Customer_data = pd.read_csv("quickbasket_customer_data.csv")

## 3. Data Understanding

In [146]:
Customer_data.head()

  customer_id signup_date       city  ...   top_category  days_since_last_order churned_next_60d
0     C101752  2026-01-31    Chennai  ...        Staples                      8                0
1     C100454  2026-04-20  Bengaluru  ...         Snacks                      8                0
2     C100671  2026-04-03      Delhi  ...  Personal Care                      6                1
3     C102246  2025-05-30     Mumbai  ...      Household                      7                0
4     C105913  2025-02-09     Mumbai  ...    Meat & Fish                     29                0

[5 rows x 27 columns]

In [147]:
print("Actual Customer data, \n Record count :",Customer_data.shape[0],"\n Feature Count",Customer_data.shape[1])

Actual Customer data,
 Record count : 6030
 Feature Count 27

In [148]:
Customer_data.dtypes

customer_id                    object
signup_date                    object
city                           object
warehouse_id                   object
age                           float64
gender                         object
acquisition_channel            object
first_order_discount_pct        int64
membership_plan                object
tenure_days                     int64
orders_last_90d                 int64
avg_order_value_inr           float64
avg_delivery_fee_inr          float64
avg_delivery_time_min         float64
late_delivery_pct             float64
order_cancellation_pct        float64
missing_or_wrong_items_pct    float64
support_tickets_90d             int64
avg_ticket_resolution_hrs     float64
last_csat_score               float64
app_store_rating_given        float64
app_sessions_per_week         float64
coupon_usage_pct              float64
preferred_payment              object
top_category                   object
days_since_last_order           int64
churned_next_60d                int64
dtype: object

In [149]:
Customer_data.nunique() # Unique value of each field

customer_id                   6000
signup_date                    690
city                             6
warehouse_id                     9
age                             47
gender                           3
acquisition_channel              5
first_order_discount_pct         6
membership_plan                  3
tenure_days                    690
orders_last_90d                 22
avg_order_value_inr            947
avg_delivery_fee_inr             6
avg_delivery_time_min          387
late_delivery_pct              532
order_cancellation_pct         156
missing_or_wrong_items_pct     163
support_tickets_90d              6
avg_ticket_resolution_hrs      437
last_csat_score                  5
app_store_rating_given           5
app_sessions_per_week          119
coupon_usage_pct               934
preferred_payment                5
top_category                     7
days_since_last_order           87
churned_next_60d                 2
dtype: int64

## 4. Data Cleaning

In [150]:
Customer_data.drop_duplicates(inplace=True) #Removing Duplicate Entries

In [151]:
#After removing Duplicates
print("Customer data After removing duplicates, \n Record count :",Customer_data.shape[0],"\n Feature Count",Customer_data.shape[1])

Customer data After removing duplicates,
 Record count : 6000
 Feature Count 27

In [152]:
Customer_data.isna().sum() # Total number of null entries
print(Customer_data.isna().sum()[Customer_data.isna().sum() > 0])

age                            60
gender                         25
avg_order_value_inr            40
avg_ticket_resolution_hrs    3016
last_csat_score              2151
app_store_rating_given       4830
dtype: int64

In [153]:
missing_summary = pd.DataFrame({
    "missing_count": Customer_data.isnull().sum(),
    "missing_percentage": (
        Customer_data.isnull().mean() * 100
    ).round(2)
})

print(missing_summary[missing_summary["missing_count"] > 0])

                           missing_count  missing_percentage
age                                   60                1.00
gender                                25                0.42
avg_order_value_inr                   40                0.67
avg_ticket_resolution_hrs           3016               50.27
last_csat_score                     2151               35.85
app_store_rating_given              4830               80.50

In [154]:
print("Total null entries in age column before cleanup is",Customer_data["age"].isna().sum())

Total null entries in age column before cleanup is 60

In [155]:
Customer_data["age"] = Customer_data["age"].fillna(Customer_data["age"].median())
print("Total null entries in age column after cleanup is",Customer_data["age"].isna().sum())

Total null entries in age column after cleanup is 0

In [156]:
print("Total null entries in age column before cleanup is",Customer_data["gender"].isna().sum())
print("Genders in Data set before cleanup \n",Customer_data["gender"].value_counts())

Total null entries in age column before cleanup is 25
Genders in Data set before cleanup
 gender
Male      3037
Female    2818
Other      120
Name: count, dtype: int64

In [157]:
Customer_data["gender"] = Customer_data["gender"].fillna("UNKNOWN")
print("Total null entries in age column after cleanup is",Customer_data["gender"].isna().sum())
print("Genders in Data set after cleanup \n",Customer_data["gender"].value_counts())

Total null entries in age column after cleanup is 0
Genders in Data set after cleanup
 gender
Male       3037
Female     2818
Other       120
UNKNOWN      25
Name: count, dtype: int64

In [158]:
Customer_data.describe()

               age  first_order_discount_pct  tenure_days  ...  coupon_usage_pct  days_since_last_order  churned_next_60d
count  6000.000000               6000.000000  6000.000000  ...       6000.000000            6000.000000       6000.000000
mean     32.084167                 15.666667   374.234500  ...         37.038767              19.353167          0.227167
std       8.567963                 14.448426   200.993579  ...         23.177172              12.818066          0.419036
min      18.000000                  0.000000    30.000000  ...          0.000000               2.000000          0.000000
25%      26.000000                  0.000000   198.000000  ...         19.775000              10.000000          0.000000
50%      32.000000                 10.000000   375.000000  ...         33.900000              16.000000          0.000000
75%      38.000000                 20.000000   546.250000  ...         51.400000              25.000000          0.000000
max      69.000000                 50.000000   719.000000  ...        100.000000             120.000000          1.000000

[8 rows x 18 columns]

In [160]:
Customer_data["avg_order_value_inr"].fillna(Customer_data["avg_order_value_inr"].median(),inplace=True)

In [161]:
Customer_data.sort_values(by="avg_order_value_inr",ascending=True)

     customer_id signup_date       city  ...   top_category  days_since_last_order churned_next_60d
36       C100849  2025-10-19       Pune  ...  Personal Care                      5                0
4447     C105589  2025-02-13      Delhi  ...         Snacks                     10                0
4919     C100523  2026-03-13      Delhi  ...   Fruits & Veg                     29                0
3026     C102513  2025-02-17  Bengaluru  ...        Staples                     27                0
5096     C100313  2026-04-30     Mumbai  ...        Staples                     24                1
...          ...         ...        ...  ...            ...                    ...              ...
1965     C105551  2025-09-29  Bengaluru  ...   Fruits & Veg                     24                0
5738     C103317  2025-10-23  Bengaluru  ...  Personal Care                     14                0
1150     C103252  2026-08-08     Mumbai  ...         Snacks                     15                1
1418     C101972  2025-02-18  Hyderabad  ...    Meat & Fish                     15                0
5232     C105154  2025-12-14  Bengaluru  ...        Staples                      9                1

[6000 rows x 27 columns]

In [162]:
print(Customer_data.isnull().sum()[Customer_data.isnull().sum() > 0])

avg_ticket_resolution_hrs    3016
last_csat_score              2151
app_store_rating_given       4830
dtype: int64

## 5. Data Prepration

In [164]:
X = Customer_data.drop(columns=["customer_id","signup_date","churned_next_60d"])
y = Customer_data["churned_next_60d"]

In [165]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,shuffle=True,random_state=123,stratify=y)

In [169]:
X_train.shape , y_train.shape # Training sample

((4800, 24), (4800,))

In [170]:
X_test.shape, y_test.shape #Testing sample

((1200, 24), (1200,))